### PR TITLE
Load assets only once + use snippet's html code instead of iframes + some other things.

### PR DESCRIPTION
**Pull request by sylvainjule**
I had issues with erratic previews (iframe requests randomly returning 500 errors), and improved some things for my usage. PRing this in case it can be helpful. Overall it's making the field behave much faster, with no delay between edit and preview view. As for the previous ones, do what you want with this. Here's what it does:

**1. Use cache instead of session**

Kirby now enables setting a custom cache with your plugin's name. 
Not useful anymore though if there's only 1 call / block (see below).

**2. Load assets only once**

With the current implementation, if I have 15 builder blocks with the same css file, there will be 15 requests made and the file will be loaded 15 times. 
- I have taken css and js out of the requests
- Made them a php computed returning an array of unique values ([here](https://github.com/sylvainjule/kirby-v3-builder/blob/3231a891a1ccbd7a091277d16ecfcae1e0c6ad39/config.php#L40-L57)).
- Loop through each one at the `builder-field` level ([here](https://github.com/sylvainjule/kirby-v3-builder/blob/3231a891a1ccbd7a091277d16ecfcae1e0c6ad39/src/components/BuilderField.vue#L8-L9)).

**3. Minimize http requests + return the html snippet instead of using iframes**

Instead of making a first call to store the content, wait for the response, make a second call through the iframe and dynamically set the height on load, I've kept it to [a single call returning the snippet's html](https://github.com/sylvainjule/kirby-v3-builder/blob/3231a891a1ccbd7a091277d16ecfcae1e0c6ad39/config.php#L85-L116) and rendering it [in a div](https://github.com/sylvainjule/kirby-v3-builder/blob/3231a891a1ccbd7a091277d16ecfcae1e0c6ad39/src/components/BuilderBlock.vue#L64). Feels much faster. I'm curious why you went for an iframe, is it to keep css / js files separated to prevent interferences? I'd prefer having less interactivity in previews and making sure to make my css specific, if in return I have shorter times before first-preview.

**4. Add distinct status + status styles**

Same as previous PR, added [distinct status](https://github.com/sylvainjule/kirby-v3-builder/blob/3231a891a1ccbd7a091277d16ecfcae1e0c6ad39/src/components/BuilderBlock.vue#L153-L174), `closed | preview | edit` class to each builder block, and some custom styling in order to make every state clearer (in my opinion).

It also mimics the structure field edit box and align some other details (padding inside structure edit box, box-shadow) to the panel styling, for consistency with the rest of the panel.

builder-styles

### CODE REVIEW

**Comment by TimOetting** [comment]
Hey @sylvainjule thanks a lot for your effort to write those extensive PR explanations. 

**1.** Utilizing the session for this kind of stuf never felt right anyway. I will have a look on the caching possibilities.

**2. and 3.** I didn't look this up in my devtools until now, but I assumed that the browser would be intelligent enough to only load the assets once even though they are triggered by different iframes. 
My motivation to put the preview inside iframes was indeed to keep the preview's assets separated from the panel's assets and vice versa. I had some trouble with the old Kirby Builder where a normalization script from my preview affected the panel css. You can prevent this by scoping your css/js correctly but even though it is a best practice, it is a bit to much to require from all the developers out there. Not 100% sure about this, but another problem would occure when you want to use your own version of Vue.js in your preview.
When I started implementing the preview feature I startet with the approach to fetch the preview directly, and then to inject the content into an empty iframe. Right now I just remember that I had to wrap my head around some weird issues in how the iframe behaved with this approach, gave up on this and let the iframe load its content by itself. I will have another look in this, but I will prefer to keep the preview inside iFrames.

**4.** I totally get you point to keep the style consistent with kriby's style guide. However, I find the contrast between the preview and edit mode too big. Considering that the user can not only have one block in edit mode and even mix up blocks with and without preview mode you would end up with visually prominent preview blocks and visually restrained edit blocks next to each other. I will, however, adapt the class modifiers so that anyone can add distinct stylings via a custom panel style.

**Comment by sylvainjule** [comment]
Had an issue with broken kirbytext `image` tags. This is because the tags assumes the `$tag` variable [returns the parent page object the search the file](https://github.com/k-next/kirby/blob/afa6cae12965abe383a8797c37337de0a5b75e68/config/tags.php#L98), else it'll [construct the url](https://github.com/k-next/kirby/blob/afa6cae12965abe383a8797c37337de0a5b75e68/config/tags.php#L104) from the website's base url. So instead ended up with `http://my.website/image.jpg`.

So passing the files array of the parent page fixes it. I'd assume passing children too could be useful.

**Comment by sylvainjule** [comment]
I don't have this issue, I'm guessing it's because one of your builder blocks doesn't have a `preview` option to set its snippet?

``` 
myblock:
  preview:
    snippet: builder/my-snippet
```

**Comment by jschopplich** [comment]
Exactly. But in my opinion the preview should not be a requirement. Like I used the plugin before. I guess it's a easy fix to ignore the preview if it isn't set?

**Comment by jschopplich** [comment]
@sylvainjule I can't open an new issue on your fork. Therefore quick bug report here:

Tabs won't work no more since your changes. They are not clickable nor can I open other tabs. You can use the test blueprint Tim put in his readme.

grafik

**Pull request closed without merging**
